### PR TITLE
Highlight default option in prompts

### PR DESCRIPTION
**Pull request by neurocyte**
This helps the user know which option take effect if they just press enter.

### CODE REVIEW

**Comment by nektro** [comment]
Do you have a screenshot of a before/after?

**Comment by neurocyte** [comment]
Before:
image

After:
image

**Comment by nektro** [comment]
Can you remove the bold wrapping? Other than that, looks great! Thanks for the PR 💯

**Comment by neurocyte** [comment]
Updated. Now without the bold:
image

**Comment by nektro** [comment]
I wonder if Faint and Bold cancel eachother out or it goes bold. Can you use brackets on the if and try
```zig
try out.print(ansi.style.ResetIntensity, .{});
try out.print(comptime ansi.color.Fg(.Cyan, f.name), .{});
try out.print(ansi.style.Faint, .{});
```

**Comment by neurocyte** [comment]
That looks like this:
image

Much nicer.

**Comment by nektro** [comment]
Thanks!

**Pull request merged**
